#!/bin/bash
# Copyright 2017-2018 Obsidian-Studios, Inc.
# Distributed under the terms of the GNU General Public License v2

: ${CATALINA_HOME:=@GENTOO_PORTAGE_EPREFIX@/usr/share/tomcat-@SLOT@/}
: ${TOMCATS_BASE:=@GENTOO_PORTAGE_EPREFIX@/var/lib/tomcat/}
: ${CATALINA_BASE:=${TOMCATS_BASE}tomcat-@SLOT@/}
: ${CATALINA_TMPDIR:=@GENTOO_PORTAGE_EPREFIX@/var/tmp/tomcat/tomcat-@SLOT@/}
: ${CATALINA_WORKDIR:=${CATALINA_TMPDIR}}

: ${TOMCAT_START:=start}

: ${JPDA_TRANSPORT:="dt_socket"}
: ${JPDA_ADDRESS:="8000"}
: ${JPDA_OPTS="-Xdebug -Xrunjdwp:transport=$JPDA_TRANSPORT,address=$JPDA_ADDRESS,server=y,suspend=n"}

if [[ -z "${CATALINA_BASE}" ]]; then
	if [[ -z "${CATALINA_INSTANCE}" ]]; then
		CATALINA_BASE="${CATALINA_BASE}"
	else
		CATALINA_BASE="${TOMCATS_BASE}${CATALINA_INSTANCE}"
	fi
fi

export JAVA_HOME=`jem ${TOMCAT_JVM:+--select-vm ${TOMCAT_JVM}} --jre-home`
CLASSPATH="${CATALINA_HOME}/bin/tomcat-bootstrap.jar"
CLASSPATH+=":${CATALINA_HOME}/bin/tomcat-juli.jar"
export CLASSPATH

if [[ "$1" == "start" ]]; then
	if [[ ! -e "${CATALINA_TMPDIR}" ]]; then
		eerror "CATALINA_TMPDIR does not exist. Unable to start tomcat."
		eerror "Please see @GENTOO_PORTAGE_EPREFIX@/etc/conf.d/tomcat-@SLOT@ for more information."
		exit 1
	fi

	cmd=java args=
	if [[ "${TOMCAT_START}" == "debug" ]] || \
		[[ "${TOMCAT_START}" == "-security debug" ]] ; then
		cmd=jdb
		args+=" -sourcepath ${CATALINA_HOME}/../../jakarta-tomcat-catalina/catalina/src/share"
	fi
	if [[ "${TOMCAT_START}" == "-security debug" ]] || \
		[[ "${TOMCAT_START}" == "-security start" ]]; then
		args+=" -Djava.security.manager"
		args+=" -Djava.security.policy=${CATALINA_BASE}/conf/catalina.policy"
	fi
	[[ "${TOMCAT_START}" == "jpda start" ]] && args+=" ${JPDA_OPTS}"

	args+=" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager"
	args+=" -Djava.util.logging.config.file=${CATALINA_BASE}/conf/logging.properties"

	cd "${CATALINA_WORKDIR}"

	export TOMCAT_SS_CMD=${JAVA_HOME}/bin/${cmd}
	export TOMCAT_SS_ARGS="${JAVA_OPTS} \
		${JAVA_INSTANCE_OPTS} \
		${args} \
		-Dcatalina.base=${CATALINA_BASE} \
		-Dcatalina.home=${CATALINA_HOME} \
		-Djava.io.tmpdir=${CATALINA_TMPDIR} \
		-classpath ${CLASSPATH} \
		org.apache.catalina.startup.Bootstrap \
		${CATALINA_OPTS} \
		${TOMCAT_START}"
elif [[ "$1" == "stop" ]]; then
	export TOMCAT_SS_CMD=${JAVA_HOME}/bin/java
	export TOMCAT_SS_ARGS="${JAVA_OPTS} \
		${JAVA_INSTANCE_OPTS} \
		-Dcatalina.base=${CATALINA_BASE} \
		-Dcatalina.home=${CATALINA_HOME} \
		-Djava.io.tmpdir=${CATALINA_TMPDIR} \
		-classpath ${CLASSPATH} \
		org.apache.catalina.startup.Bootstrap \
		${CATALINA_OPTS} \
		stop"
fi

[[ -z "${RC_SVCNAME}" ]] &&
	${TOMCAT_SS_CMD:=${JAVA_HOME}/bin/java} ${TOMCAT_SS_ARGS}
